### ISSUE TITLE
Blocktrail API being deprecated soon

### ISSUE THREAD

**Issue by rubensayshi** [yunixon/blocktrail#5]
Hey @yunixon, 

I'm the CTO @ Blocktrail, super awesome that you're implementing a ruby wrapper for our data API!

But I have some sad news for you; we're actually deprecating our API (we're sending out newsletter upcoming week to our dev users I think to announce this)...

Blocktrail was acquired by Bitmain and we've been in the process of rebranding to BTC.com, we'll actually move our dev users to our BTC.com data API soon.

atm the BTC.com data API has tighter rate limits than the Blocktrail API, but this should be changed to similar rate limits somewhere this week!

The BTC.com data API actually has more or less the same data as the Blocktrail API and it's backend is a lot better than the Blocktrail API so that's why we've made this choice.

You can find the docs here https://btc.com/api-doc

Sorry :/

**Comment by yunixon** [comment]
Hey @rubensayshi, thanks for clarifying

**Comment by Sailias** [comment]
@rubensayshi we're using this gem in another project (referenced in this issue).

A developer on that project got this email:

> Tobias Hoffmann (BTC.com)
> Mar 16, 18:00 CST
> Hello,
> We are currently in the process of moving the blocktrail API under the BTC.com brand.
> Everything will be backwards compatible though and you will not have to worry about changes affecting your system logic.
> Kind regards,
> Tobias

BTC.com does not have subscriptions, is this being implemented as part of "moving the Blocktrail API under the BTC.com brand"?

**Comment by rubensayshi** [comment]
hey @Sailias sorry for the slow response, you're probably better of using support@blocktrail.com or support@btc.com for questions if you want a quick response haha.

Anyway, we've ported all Wallet API and Webhook features from Blocktrail to dev.btc.com  
The only thing that was deprecated and will shutdown soon is the Data API of Blocktrail because BTC.com already had a good (better) Data API before Blocktrail was acquired and we do not wish to maintain 2 Data API's.

For Webhooks everything will continue to operate perfectly fine, the new API endpoint is wallet-api.btc.com but we'll probably keep the api.blocktrail.com alias working forever since there's no real reason not to ...
